name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Determine changed directory
      id: changed-directory
      run: |
        current_commit_hash=$(git rev-parse --short "${{ github.sha }}")
        before_commit_hash=$(git rev-parse --short "${{ github.event.before }}")
        echo "::set-output name=current_commit::${current_commit_hash}"
        echo "::set-output name=before_commit::${before_commit_hash}"
    - name: Change directory
      run: cd ${{ steps.changed-directory.outputs.directory }}
    - name: Run tests
      run: sbt test
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
